{% set version = "1.0" %}

package:
  name: tomocupy
  version: {{ version }}

source:
  path: ../

build:
  # skip: True  # [cuda_compiler_version != "11.0"]
  # skip: True  # [py != 310]
  # skips above this line are for debugging purposes only
  skip: True  # [cuda_compiler_version in (undefined, "None")]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  channels:
    - conda-forge
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} # [cuda_compiler_version != None]
    - cmake
    - ninja
    - swig
  host:
    - cudatoolkit
    - numpy
    - pip
    - python
    - scikit-build
    - setuptools
  run:
    - {{ pin_compatible('python') }}
    - cudatoolkit
    - cupy
    - h5py
    - numexpr
    - numpy
    - opencv
    - opencv-contrib-python
    - pywavelets
    - tifffile
    - zarr    

about:
    home: https://github.com/tomography/tomocupy
    license: BSD 3-Clause
    license_family: BSD
    summary: 'GPU-based reconstruction of tomography data'
